# 服务名称
serviceName: "userExample"
# 监听地址
servicePort: 28080
# 运行环境，dev:开发环境，prod:生产环境，pre:预生产环境
serviceEnv: "dev"
# 版本
version: "v0.0.0"

# 超时，单位为秒
readTimeout: 3
writeTimeout: 90 # 如果enableProfile为true，需要大于60s，pprof做profiling的默认值是60s

# 是否开启性能分析功能，true:开启，false:关闭
enableProfile: false

# 是否开启指标采集，true:开启，false:关闭
enableMetrics: true


# 是否开启限流，true:开启，false:关闭
enableLimit: true
# limit配置
ratelimiter:
  # 限流维度，支持path和ip两种，默认是path
  dimension: "path"
  # 持续每秒允许成功请求数，默认是500
  qpsLimit: 300
  # 瞬时最大允许峰值，默认是1000，通常大于qpsLimit
  maxLimit: 600


# 是否开启链路跟踪，true:开启，false:关闭
enableTracing: true
# jaeger配置，使用agent采集
jaeger:
  agentHost: "192.168.3.37"
  agentPort: "6831"
  # 采样率，0~1之间，0表示禁止采样，大于等于1表示采样所有链路
  samplingRate: 1


log:
  level: "info" # 输出日志级别 debug, info, warn, error，默认是debug
  format: "console" # 输出格式，console或json，默认是console
  #isSave: true # false:输出到终端，true:输出到文件，默认是false
  #logFileConfig: # isSave=true时有效
  #  filename: "example.log" # 文件名称，默认值out.log
  #  maxSize: 1 # 最大文件大小(MB)，默认值10MB
  #  maxBackups: 5 # 保留旧文件的最大个数，默认值100个
  #  maxAge: 2 # 保留旧文件的最大天数，默认值30天
  #  isCompression: true # 是否压缩/归档旧文件，默认值false


# mysql配置，url格式 <user>:<pass>@(127.0.0.1:3306)/<db>?charset=utf8mb4&parseTime=true
mysqlUrl: "root:123456@(192.168.3.37:3306)/account?charset=utf8mb4&parseTime=true"

# redis配置, redis6版本以上，默认用户为default，url格式 [user]:<pass>@]127.0.0.1:6379/[db]
redisUrl: "default:123456@192.168.3.37:6379"
